
package fr.cap.wikimnv.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "profilUser", targetNamespace = "http://service.wikimnv.cap.fr/", wsdlLocation = "http://172.20.100.133:8080/WikiMNV-Core-Admin/webservices/serviceUser?wsdl")
public class ProfilUser_Service
    extends Service
{

    private final static URL PROFILUSER_WSDL_LOCATION;
    private final static WebServiceException PROFILUSER_EXCEPTION;
    private final static QName PROFILUSER_QNAME = new QName("http://service.wikimnv.cap.fr/", "profilUser");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.20.100.133:8080/WikiMNV-Core-Admin/webservices/serviceUser?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROFILUSER_WSDL_LOCATION = url;
        PROFILUSER_EXCEPTION = e;
    }

    public ProfilUser_Service() {
        super(__getWsdlLocation(), PROFILUSER_QNAME);
    }

    public ProfilUser_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROFILUSER_QNAME, features);
    }

    public ProfilUser_Service(URL wsdlLocation) {
        super(wsdlLocation, PROFILUSER_QNAME);
    }

    public ProfilUser_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROFILUSER_QNAME, features);
    }

    public ProfilUser_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfilUser_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProfilUser
     */
    @WebEndpoint(name = "profilUserPort")
    public ProfilUser getProfilUserPort() {
        return super.getPort(new QName("http://service.wikimnv.cap.fr/", "profilUserPort"), ProfilUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProfilUser
     */
    @WebEndpoint(name = "profilUserPort")
    public ProfilUser getProfilUserPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wikimnv.cap.fr/", "profilUserPort"), ProfilUser.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROFILUSER_EXCEPTION!= null) {
            throw PROFILUSER_EXCEPTION;
        }
        return PROFILUSER_WSDL_LOCATION;
    }

}
